name: mb_color_picker
description: A flexible and customizable color and gradient picker for Flutter.
version: 0.0.1
homepage: https://github.com/mikaelbotassi/mb_color_picker
repository: https://github.com/mikaelbotassi/mb_color_picker
issue_tracker: https://github.com/mikaelbotassi/mb_color_picker/issues

environment:
  sdk: ^3.11.4
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.1.0
  collection: ^1.19.1
  tabler_icons_plus: ^3.41.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
